# Generated by Django 5.1 on 2024-08-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='name',
            field=models.CharField(default='science', max_length=30),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
