# Generated by Django 5.1 on 2024-08-26 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(default=1)),
                ('address', models.JSONField(default={})),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('itemDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.itemdetails')),
                ('orderDetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.orderdetails')),
            ],
        ),
    ]
