# Generated by Django 5.1 on 2024-08-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='paymenttype',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.TextField(default='', max_length=100),
        ),
    ]
