# Generated by Django 5.1 on 2024-08-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderdetails_paymenttype_orderdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='paymenttype',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
